# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 773b326619da7a26e50ef0e4e172aaac14c937025069b2dd63dcc6c54fe8696480879b0a0f799f0b5a7cea7a2d1b1a6b12c2106f7ff4ee7e9f22329d65231bfa

test:
  secret_key_base: cacc225478b7c95866d3161bc922ded484f13cdf0fc2537a07548661a789fd6399392c912095e0ac65205b4d1d0a32ddb6fa097a8dfc1fb7a2155dc5959cd0b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
